"""add_vendor_types_return_tracking

Revision ID: 18e7191c4a73
Revises: e7f8g9h0i1j2
Create Date: 2026-07-19 05:09:53.884815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '18e7191c4a73'
down_revision: Union[str, Sequence[str], None] = 'e7f8g9h0i1j2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(name: str) -> bool:
    insp = inspect(op.get_context().connection.engine)
    return name in insp.get_table_names()

def column_exists(table: str, column: str) -> bool:
    insp = inspect(op.get_context().connection.engine)
    cols = [c["name"] for c in insp.get_columns(table)]
    return column in cols


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_context().connection
    insp = inspect(conn.engine)

    if not table_exists('vendor_types'):
        op.create_table('vendor_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if not table_exists('return_photos'):
        op.create_table('return_photos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_item_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not column_exists('order_items', 'quantity_returned'):
        op.add_column('order_items', sa.Column('quantity_returned', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    if not column_exists('order_items', 'quantity_damaged'):
        op.add_column('order_items', sa.Column('quantity_damaged', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    if not column_exists('vendors', 'vendor_type_id'):
        op.add_column('vendors', sa.Column('vendor_type_id', sa.Integer(), nullable=True))
        if table_exists('vendor_types'):
            op.create_foreign_key('fk_vendors_vendor_type', 'vendors', 'vendor_types', ['vendor_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'vendor_type_id')
    op.drop_column('order_items', 'quantity_damaged')
    op.drop_column('order_items', 'quantity_returned')
    op.drop_table('return_photos')
    op.drop_table('vendor_types')
    # ### end Alembic commands ###
