"""Phase 8: Add is_container, InventoryItemAttribute, location-based order prefixes

Revision ID: bd0c719effb1
Revises: 18e7191c4a73
Create Date: 2026-07-20 20:47:25.603523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0c719effb1'
down_revision: Union[str, Sequence[str], None] = '18e7191c4a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _has_column(table: str, column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = [c["name"] for c in inspector.get_columns(table)]
    return column in cols


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('inventory_item_attributes'):
        op.create_table('inventory_item_attributes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('attribute_name', sa.String(length=100), nullable=False),
        sa.Column('attribute_value', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_id', 'attribute_name', name='uq_item_attribute')
        )
        op.create_index('idx_item_attr_name', 'inventory_item_attributes', ['attribute_name'], unique=False)
    
    if not _has_column('inventory_items', 'is_container'):
        op.add_column('inventory_items', sa.Column('is_container', sa.Boolean(), nullable=False, server_default=sa.false()))
    
    # Check if FK already exists before creating
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = [fk['name'] for fk in inspector.get_foreign_keys('inventory_items')]
    if not any('parent_id' in str(fk) for fk in fks):
        try:
            op.create_foreign_key(None, 'inventory_items', 'inventory_items', ['parent_id'], ['id'])
        except Exception:
            pass  # FK might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'is_container')
    op.drop_index('idx_item_attr_name', table_name='inventory_item_attributes')
    op.drop_table('inventory_item_attributes')
    # ### end Alembic commands ###
