"""Schema package.

Split of the legacy monolith ``app/schemas.py`` into domain-focused modules.
Every name previously exported from ``app.schemas`` is re-exported here for
100% backward compatibility::

    from app.schemas import OrderResponse   # still works

Import the focused modules directly for new code::

    from app.schemas.order import OrderResponse
"""
from app.schemas.auth import (
    LoginRequest,
    UserBase,
    PermissionSchema,
    RoleSchema,
    UserResponse,
    TokenResponse,
    RefreshTokenRequest,
    RoleCreate,
    RoleUpdate,
    UserCreate,
    UserUpdate,
    PasswordResetRequest,
    PasswordResetConfirm,
    PasswordResetResponse,
    SignatureResponse,
    SignatureUpdate,
)
from app.schemas.vendor import (
    VendorBase,
    VendorCreate,
    VendorUpdate,
    VendorResponse,
    VendorSummaryResponse,
    VendorTypeResponse,
    VendorTypeCreate,
)
from app.schemas.inventory import (
    InventoryCategoryBase,
    InventoryCategoryCreate,
    InventoryCategoryResponse,
    InventoryItemBase,
    InventoryItemCreate,
    InventoryItemChildCreate,
    InventoryItemBatchCreate,
    InventoryItemUpdate,
    InventoryItemResponse,
    InventoryItemDetailResponse,
    InventoryTransactionResponse,
    InventoryItemImageCreate,
    InventoryItemImageResponse,
    SerialNumberCreate,
    SerialNumberBatchCreate,
    SerialNumberImportCreate,
    SerialNumberUpdate,
    SerialNumberResponse,
    RestockRequest,
    AdjustmentRequest,
)
from app.schemas.order import (
    OrderItemCreateRequest,
    OrderItemResponse,
    ReturnItemRequest,
    ReturnOrderRequest,
    OrderCreateRequest,
    OrderUpdateRequest,
    OrderTimelineEntryResponse,
    OrderResponse,
    NotificationResponse,
    DispatchItemRequest,
    DispatchRequestBody,
    DocumentUploadRequest,
    DocumentResponse,
    DocumentVersionHistoryResponse,
)
from app.schemas.common import (
    SettingsResponse,
    SettingsUpdate,
    PaginationParams,
    PaginatedResponse,
    AuditLogResponse,
    ApprovalRuleCondition,
    ApprovalRuleCreateRequest,
    ApprovalRuleResponse,
    ErrorResponse,
)
from app.schemas.warehouse import (
    WarehouseBinResponse,
    WarehouseShelfResponse,
    WarehouseRackResponse,
    WarehouseZoneResponse,
    WarehouseResponse,
)

__all__ = [
    # auth
    "LoginRequest",
    "UserBase",
    "PermissionSchema",
    "RoleSchema",
    "UserResponse",
    "TokenResponse",
    "RefreshTokenRequest",
    "RoleCreate",
    "RoleUpdate",
    "UserCreate",
    "UserUpdate",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "PasswordResetResponse",
    "SignatureResponse",
    "SignatureUpdate",
    # vendor
    "VendorBase",
    "VendorCreate",
    "VendorUpdate",
    "VendorResponse",
    "VendorSummaryResponse",
    "VendorTypeResponse",
    "VendorTypeCreate",
    # inventory
    "InventoryCategoryBase",
    "InventoryCategoryCreate",
    "InventoryCategoryResponse",
    "InventoryItemBase",
    "InventoryItemCreate",
    "InventoryItemChildCreate",
    "InventoryItemBatchCreate",
    "InventoryItemUpdate",
    "InventoryItemResponse",
    "InventoryItemDetailResponse",
    "InventoryTransactionResponse",
    "InventoryItemImageCreate",
    "InventoryItemImageResponse",
    "SerialNumberCreate",
    "SerialNumberBatchCreate",
    "SerialNumberImportCreate",
    "SerialNumberUpdate",
    "SerialNumberResponse",
    "RestockRequest",
    "AdjustmentRequest",
    # order
    "OrderItemCreateRequest",
    "OrderItemResponse",
    "ReturnItemRequest",
    "ReturnOrderRequest",
    "OrderCreateRequest",
    "OrderUpdateRequest",
    "OrderTimelineEntryResponse",
    "OrderResponse",
    "NotificationResponse",
    "DispatchItemRequest",
    "DispatchRequestBody",
    "DocumentUploadRequest",
    "DocumentResponse",
    "DocumentVersionHistoryResponse",
    # common
    "SettingsResponse",
    "SettingsUpdate",
    "PaginationParams",
    "PaginatedResponse",
    "AuditLogResponse",
    "ApprovalRuleCondition",
    "ApprovalRuleCreateRequest",
    "ApprovalRuleResponse",
    "ErrorResponse",
    # warehouse
    "WarehouseBinResponse",
    "WarehouseShelfResponse",
    "WarehouseRackResponse",
    "WarehouseZoneResponse",
    "WarehouseResponse",
]
